const permissions = {
  // USER
  VIEW_USER: "VIEW_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",

  // QUESTION
  CREATE_QUESTION: "CREATE_QUESTION",
  VIEW_QUESTION: "VIEW_QUESTION",
  EDIT_QUESTION: "EDIT_QUESTION",
  DELETE_QUESTION: "DELETE_QUESTION",

  // ANSWER
  CREATE_ANSWER: "CREATE_ANSWER",
  VIEW_ANSWER: "VIEW_ANSWER",
  EDIT_ANSWER: "EDIT_ANSWER",
  DELETE_ANSWER: "DELETE_ANSWER",

  // USER PROFILE
  CREATE_USER_PROFILE: "CREATE_USER_PROFILE",
  VIEW_USER_PROFILE: "VIEW_USER_PROFILE",
  EDIT_USER_PROFILE: "EDIT_USER_PROFILE",
  DELETE_USER_PROFILE: "DELETE_USER_PROFILE",

  // COMPANY PROFILE
  CREATE_COMPANY_PROFILE: "CREATE_COMPANY_PROFILE",
  VIEW_COMPANY_PROFILE: "VIEW_COMPANY_PROFILE",
  EDIT_COMPANY_PROFILE: "EDIT_COMPANY_PROFILE",
  DELETE_COMPANY_PROFILE: "DELETE_COMPANY_PROFILE",

  //   JOB
  CREATE_JOB: "CREATE_JOB",
  VIEW_JOB: "VIEW_JOB",
  EDIT_JOB: "EDIT_JOB",
  DELETE_JOB: "DELETE_JOB",

  //   EVENT
  CREATE_EVENT: "CREATE_EVENT",
  VIEW_EVENT: "VIEW_EVENT",
  EDIT_EVENT: "EDIT_EVENT",
  DELETE_EVENT: "DELETE_EVENT",

  //   POLL
  CREATE_POLL: "CREATE_POLL",
  VIEW_POLL: "VIEW_POLL",
  EDIT_POLL: "EDIT_POLL",
  DELETE_POLL: "DELETE_POLL",

  //   POST
  CREATE_POST: "CREATE_POST",
  VIEW_POST: "VIEW_POST",
  EDIT_POST: "EDIT_POST",
  DELETE_POST: "DELETE_POST",

  //   COMMENT
  CREATE_COMMENT: "CREATE_COMMENT",
  VIEW_COMMENT: "VIEW_COMMENT",
  EDIT_COMMENT: "EDIT_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",

  //   REPLY
  CREATE_REPLY: "CREATE_REPLY",
  VIEW_REPLY: "VIEW_REPLY",
  EDIT_REPLY: "EDIT_REPLY",
  DELETE_REPLY: "DELETE_REPLY",

  //   GROUP
  CREATE_GROUP: "CREATE_GROUP",
  VIEW_GROUP: "VIEW_GROUP",
  EDIT_GROUP: "EDIT_GROUP",
  DELETE_GROUP: "DELETE_GROUP",

  //   MESSAGE
  CREATE_MESSAGE: "CREATE_MESSAGE",
  VIEW_MESSAGE: "VIEW_MESSAGE",
  EDIT_MESSAGE: "EDIT_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
};
