const questionCategories = [
  "General Programming",
  "Web Development",
  "Mobile App Development",
  "Frontend Development",
  "Backend Development",
  "Database Management",
  "Algorithms and Data Structures",
  "DevOps",
  "UI/UX Design",
  "Software Testing",
  "Networking",
  "Cybersecurity",
  "Cloud Computing",
  "Machine Learning",
  "Artificial Intelligence",
  "Internet of Things (IoT)",
  "Game Development",
  "Version Control (Git)",
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "TypeScript",
  "Frameworks and Libraries",
  "React.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Ruby on Rails",
  "Laravel",
  "Spring Boot",
  "ASP.NET",
  "Flutter",
  "React Native",
  "jQuery",
  "Bootstrap",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "OpenCV",
  "Others",
];

const errorCategories = [
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Dart",
  "TypeScript",
  "React.js",
  "Angular.Js",
  "Vue.js",
  "Node.js",
  "Django",
  "Ruby on Rails",
  "Laravel",
  "Spring Boot",
  "ASP.NET",
  "Flutter",
  "React Native",
  "jQuery",
  "Bootstrap",
  "CSS",
  "HTML",
  "Others",
];

export { errorCategories, questionCategories };
